language: php

php:
    - 5.4
    - 5.5

before_install:
  - sudo apt -qq update
  - yes | sudo apt install php-xml php-mbstring

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - ./bin/simple-phpunit -c app
