imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver: pdo_mysql
        dbname: ope_test
        user: ope
        password: qZq8DuFyb3Dz69Bn
        charset: UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
